### ISSUE TITLE
[Bug] patch-package issue

### ISSUE THREAD

**Issue by sedghi** [Kitware/vtk-js#3231]
### Bug description

In cornerstone3D, I'm upgrading from `32.9.0` to latest (32.11.0)

I'm seeing an issue in install

```js
warning "workspace-aggregator-73df0d5d-9b8a-4e98-8968-518b57ed64b9 > @cornerstonejs/core > @kitware/vtk.js@32.11.0" has unmet peer dependency "wslink@>=1.1.0 || ^2.0.0".
[5/5] 🔨  Building fresh packages...
[7/16] ⢀ sharp
[6/16] ⢀ unix-dgram
[11/16] ⢀ @kitware/vtk.js
[8/16] ⢀ puppeteer
error /Users/alireza/dev/admin/cornerstone3D.git/main/node_modules/@kitware/vtk.js: Command failed.
Exit code: 127
Command: patch-package
Arguments: 
```

### Steps to reproduce

Clone cornerstone3D and upgrade version of vtk to 32.11.0

### Expected Behavior

  d

### Environment

- vtk.js version:32.11.0
- Browsers:Chrome
- OS:macOS

**Comment by floryst** [comment]
Fixed in #3233

**Comment by sedghi** [comment]
@floryst I still can't install it 


error /Users/alireza/dev/admin/cornerstone3D.git/main/node_modules/@kitware/vtk.js: Command failed.
Exit code: 127
Command: patch-package
Arguments:

**Comment by daker** [comment]
The PR that @floryst has mentioned is has not been published on npm as you can see in the action's log

https://github.com/Kitware/vtk-js/actions/runs/13863095403/job/38796033230#step:10:49

**Comment by floryst** [comment]
Yes, I mistakenly used `chore:` when I wanted to actually push out a release. I'll get that released today.

**Comment by floryst** [comment]
The new changes should now be available in the latest published version of vtk.js.
