### ISSUE TITLE
3D View freezes when toggling visibility of Volume Rep Proxy

### ISSUE THREAD

**Issue by llangholz89** [Kitware/vtk-js#728]
Similar to [this](https://github.com/Kitware/pv-web-viewer/issues/77) issue reported in PV-Glance, the 3D view becomes unresponsive when toggling the visibility of a Volume Representation Proxy.  In my case it is the reverse scenario, I have the slice visibility on and am turning on the volume visibility when the crash occurs.  I've even rolled back the version to before the commit referenced in the Glance issue and still see the freeze.  

It came about when trying to implement [this](https://github.com/Kitware/vtk-js/pull/623/files/a32c18b9d076fb46502d0e8a67b5b00eb4d0616e#diff-cfe697c4e9081068031fd5373fb4e3af) fix for the volume mapper.  Without implementing that fix I don't get the freeze but I also don't see the volume until I click within the scene. 

These are the console errors that come out when the freeze occurs (with version 6.4.13):
```
[.Offscreen-For-WebGL-0x7fd703110800]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: <- error from previous GL command
[.Offscreen-For-WebGL-0x7fd703110800]GL ERROR :GL_INVALID_OPERATION : GetShaderiv: <- error from previous GL command
[.Offscreen-For-WebGL-0x7fd703110800]GL ERROR :GL_INVALID_OPERATION : GLES2DecoderImpl::DoBindTexImage2DCHROMIUM: <- error from previous GL command
[.Offscreen-For-WebGL-0x7fd703110800]GL ERROR :GL_INVALID_VALUE : glUniform1i: texture unit out of range
[.Offscreen-For-WebGL-0x7fd703110800]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: Source and destination textures of the draw are the same.

```
The only difference in the logs with version 6.4.23 is that I don't see the last one.

Any thoughts or updates from the similar issue in Glance?
Thanks!
-Logan

**Comment by martinken** [comment]
I cannot seem to reproduce this but I am working directly with the volume and image actors/mappers. Modifying testIntermixedImage to add the volume or image 5 seconds after the other no matter what order I do it in it seems to work. I'll try digging a bit more to see if I can track down the issue.

**Comment by floryst** [comment]
@llangholz89 Do you happen to have a small test case demonstrating the issue that you can share? Glance has a lot of moving parts to sift through, and if you have a test case you can share that would be great.

**Comment by martinken** [comment]
OK digging further this only seems to happen when the cube axes thing is visible.

I tried adding a second overlayed renderer to the intermeixedimage test but it still doesn't fail. Maybe there is something in how the representation is setting up the cube axes and main viewport.

**Comment by llangholz89** [comment]
@floryst unfortunately the application I'm working within has a lot of moving parts as well, but I'll see if I can reproduce it in a smaller test case.

@martinken Thanks for looking into this! Regarding the cube axis - I currently have that disabled in my view but I can take a look into that as well.

Thanks for the help!

**Comment by martinken** [comment]
OK I was able to reproduce the issue by adding the orientation widget to my example. I'll let you know what I find.

**Comment by martinken** [comment]
Notes:  Left mouse up cancels animation mode, during that it does a render which binds the current framebuffer which modifies the renderwindow which then invokes a callback on the orientation marker that invokes a nested render which causes the issues.

**Comment by martinken** [comment]
Should be fixed by https://github.com/Kitware/vtk-js/pull/733

**Comment by llangholz89** [comment]
@martinken 
Yep, that fixed the issue I was seeing. Thanks for looking into this! 
I still get the `glFrameBufferTexture2D` and `glUniform1i: texture unit out of range` console errors, but they don't seem to crash anything.  
Thanks for the help!
